name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build -- --base-href "/"

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
        with:
          branch: deploy
          folder: dist/website/browser
