name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build -- --base-href "/"

      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: dist/website/browser

  deploy:
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: github-pages
          timeout: 12000000
